version: '3.8'


volumes:
  local_pgdata:
  pgadmin-data:

services:
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always

    volumes:
      - pgadmin-data:/var/lib/pgadmin
    
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

    ports:
      - "5050:80"

  database:
    image: 'postgres:14.4'
    container_name: local_pgdb


    ports:
      - 2999:5432

    environment:
      - POSTGRES_USER=puresify
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=puresifydb


    volumes:
      - local_pgdata:/var/lib/postgresql/data
